### ISSUE TITLE
Radius parameter for search is not exposed

### ISSUE THREAD

**Issue by cjrh** [lerouxrgd/ngt-rs#11]
Hi @lerouxrgd 

I was interested to use the `radius` parameter for search, but I see that it is only exposed in `QGQuery` and not for regular search:

![image](https://user-images.githubusercontent.com/480395/230055813-a7b6b595-5960-40a2-b494-f6e37b89d1ae.png)

Was there a specific reason for that, or is it just waiting for someone to make a PR to expose that?

**Comment by lerouxrgd** [comment]
Hello,

I indeed hard-coded it to mirror Python implementation as you can see [here](https://github.com/yahoojapan/NGT/blob/main/python/ngt/base.py#L347).

However the C API contains a [ngt_search_index_with_query](https://github.com/yahoojapan/NGT/blob/main/lib/NGT/Capi.h#L126) that takes a `NGTQuery` with multiple [parameters](https://github.com/yahoojapan/NGT/blob/main/lib/NGT/Capi.h#L40-L47). So I think the best would be to expose it, I will look into it.

**Comment by lerouxrgd** [comment]
@cjrh this issue has been pending for some time but I have finally managed to tackle it after updating NGT to version 2.

This has been implemented in version `0.6.0`, let me know if that works for you.

**Comment by cjrh** [comment]
Thank you!
